### ISSUE TITLE
pip install for Python <=3.7 is v. 0.0.1

### ISSUE THREAD

**Issue by jlmaurer** [ACCESS-Cloud-Based-InSAR/dem-stitcher#27]
Platform: 
Mac OS Big Sur, 11.6.4 (20G417) AND google Colab
Python v. 3.7

"pip install dem-stitcher" 
Output: 
`Successfully installed dem-stitcher-0.0.1`

It seems only 0.0.1 gets installed with Python <=3.7. Can you make this and/or a prior version compatible with at least Python=3? This is quite useful for Google Colab in particular, which only runs python 3.7.

**Comment by jhkennedy** [comment]
@jlmaurer  in #28, I've lowered the minimum python version to 3.7 since it's [EOL isn't until next summer](https://endoflife.date/python). I'll push out a release ASAP. 

That said, Numpy and many packages have all dropped support for Python 3.7 [as of December](https://numpy.org/neps/nep-0029-deprecation_policy.html), so I wouldn't expect 3.7 support to stick around long here. 

It might be worth, if your working in colab a lot, adding your voice to this issue to get colab updated:
https://github.com/googlecolab/colabtools/issues/2165
