### ISSUE TITLE
Access NASADEM Water Body layer (SWB)

### ISSUE THREAD

**Issue by konstantinklemmer** [ACCESS-Cloud-Based-InSAR/dem-stitcher#55]
Hi! 

First of all, thanks for the great package. I was wondering if there is a simple way to access the water bodies layer of the NASADEM-HGT product. It is listed [here](https://lpdaac.usgs.gov/products/nasadem_hgtv001/) as the third layer. I assume your `stitch_dem` function always returns the first layer only?

In the `merge_and_transform_dem_tiles` function there are two calls where you set:

```
dem_arr = dem_arr[0, ...]
```

I assume this is where you drop all but the first layer (i.e. all but the DEM layer)?

I hope the question is somewhat clear; please let me know if not.

Best,
Konstantin

**Comment by cmarshak** [comment]
Hey Konstantin,

It's not in the scope of this package. I can share with you the rough idea of how you might approach this.

1. The urls will be the same as for NASADEM.

```
from dem_stitcher.datasets import get_overlapping_dem_tiles

urls = get_overlapping_dem_tiles([-121.5, 34.95, -120.2, 36.25], 'nasadem').url.tolist()
```

Note: if you unzip a url, you will find the `*.swb` layer in the unzipped directory.

2. Modify these mostly stand-alone [functions](https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/blob/dev/dem_stitcher/dem_readers.py#L46-L67) (or reorganize them) to read the `swb` layer instead of the `hgt` layer. Might need a little bit of work (haven't tried it) because SRTM has its own gdal driver: https://gdal.org/drivers/raster/srtmhgt.html, but `swb` does not. You could infer the geometadata from the `hgt` file and then just generate a dataset.

Hope this helps. Good luck!

**Comment by konstantinklemmer** [comment]
Thanks for the swift reply!
